"use client";

import React, { useState } from 'react';
import { cn } from '@/lib/utils';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { 
  AlertTriangle, 
  CheckCircle2, 
  Clock, 
  Filter, 
  MoreVertical,
  BellRing,
  ExternalLink
} from 'lucide-react';

const initialAlerts = [
  { id: 1, severity: 'CRITICAL', device: 'device_09', zone: 'Zone 2', msg: 'Leaf Wetness threshold exceeded for 6+ hours. Pathogen infection likely.', time: '10:24 AM', resolved: false },
  { id: 2, severity: 'HIGH', device: 'device_10', zone: 'Zone 2', msg: 'High humidity (92%) detected at optimal germination temperature.', time: '09:15 AM', resolved: false },
  { id: 3, severity: 'MODERATE', device: 'device_04', zone: 'Zone 1', msg: 'Humidity rising above 70% for 3 consecutive hours.', time: '08:45 AM', resolved: true },
  { id: 4, severity: 'LOW', device: 'device_01', zone: 'Zone 1', msg: 'Temperature dropped below 15°C.', time: 'Yesterday', resolved: true },
];

export default function AlertsPage() {
  const [alerts] = useState(initialAlerts);

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight flex items-center gap-3">
            <BellRing className="h-8 w-8 text-primary neon-text" />
            Alerts Center
          </h1>
          <p className="text-muted-foreground">Manage and respond to disease risk alerts generated by the Risk Engine.</p>
        </div>
        <div className="flex gap-3">
          <Button variant="outline" className="gap-2 glass">
            <CheckCircle2 className="h-4 w-4" />
            Resolve All
          </Button>
          <Button variant="outline" className="gap-2 glass">
            <Filter className="h-4 w-4" />
            Filter by Severity
          </Button>
        </div>
      </div>

      <div className="grid gap-4">
        {alerts.map((alert) => (
          <Card key={alert.id} className={cn(
            "glass relative overflow-hidden transition-all hover:translate-x-1",
            alert.resolved ? "opacity-60" : ""
          )}>
            {!alert.resolved && (
              <div className={cn(
                "absolute left-0 top-0 bottom-0 w-1 shadow-[0_0_10px_currentcolor]",
                alert.severity === 'CRITICAL' ? 'bg-red-500 text-red-500' :
                alert.severity === 'HIGH' ? 'bg-orange-500 text-orange-500' :
                alert.severity === 'MODERATE' ? 'bg-yellow-500 text-yellow-500' : 'bg-blue-500 text-blue-500'
              )} />
            )}
            <CardContent className="p-6">
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-4">
                  <div className={cn(
                    "p-2 rounded-lg bg-background/50 border border-white/5",
                    alert.severity === 'CRITICAL' ? 'text-red-500' :
                    alert.severity === 'HIGH' ? 'text-orange-500' :
                    alert.severity === 'MODERATE' ? 'text-yellow-500' : 'text-blue-500'
                  )}>
                    <AlertTriangle className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <Badge variant="outline" className={cn(
                        "text-[10px] px-1 py-0",
                        alert.severity === 'CRITICAL' ? 'border-red-500/30 text-red-500' :
                        alert.severity === 'HIGH' ? 'border-orange-500/30 text-orange-500' :
                        alert.severity === 'MODERATE' ? 'border-yellow-500/30 text-yellow-500' : 'border-blue-500/30 text-blue-500'
                      )}>
                        {alert.severity}
                      </Badge>
                      <span className="text-[10px] text-muted-foreground font-mono">{alert.device} • {alert.zone}</span>
                    </div>
                    <p className="text-sm font-medium leading-tight">{alert.msg}</p>
                    <div className="flex items-center gap-2 mt-2 text-[10px] text-muted-foreground">
                       <Clock className="h-3 w-3" />
                       <span>Detected at {alert.time}</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                   {!alert.resolved && (
                     <Button size="sm" className="h-8 text-[10px] neon-border">Resolve Now</Button>
                   )}
                   <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-primary">
                      <ExternalLink className="h-4 w-4" />
                   </Button>
                   <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground">
                      <MoreVertical className="h-4 w-4" />
                   </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

